package g2.model;

public class Card {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Card.卡号
     *
     * @mbg.generated
     */
    private String 卡号;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Card.状态
     *
     * @mbg.generated
     */
    private String 状态;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Card.余额
     *
     * @mbg.generated
     */
    private Double 余额;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Card
     *
     * @mbg.generated
     */
    public Card(String 卡号, String 状态, Double 余额) {
        this.卡号 = 卡号;
        this.状态 = 状态;
        this.余额 = 余额;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Card
     *
     * @mbg.generated
     */
    public Card() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Card.卡号
     *
     * @return the value of Card.卡号
     *
     * @mbg.generated
     */
    public String get卡号() {
        return 卡号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Card.卡号
     *
     * @param 卡号 the value for Card.卡号
     *
     * @mbg.generated
     */
    public void set卡号(String 卡号) {
        this.卡号 = 卡号 == null ? null : 卡号.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Card.状态
     *
     * @return the value of Card.状态
     *
     * @mbg.generated
     */
    public String get状态() {
        return 状态;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Card.状态
     *
     * @param 状态 the value for Card.状态
     *
     * @mbg.generated
     */
    public void set状态(String 状态) {
        this.状态 = 状态 == null ? null : 状态.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Card.余额
     *
     * @return the value of Card.余额
     *
     * @mbg.generated
     */
    public Double get余额() {
        return 余额;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Card.余额
     *
     * @param 余额 the value for Card.余额
     *
     * @mbg.generated
     */
    public void set余额(Double 余额) {
        this.余额 = 余额;
    }
}