package g2.model;

import java.util.Date;

public class Charge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.Car_id
     *
     * @mbg.generated
     */
    private Long car_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.Use_id
     *
     * @mbg.generated
     */
    private Long use_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.Mac_id
     *
     * @mbg.generated
     */
    private Long mac_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.amount
     *
     * @mbg.generated
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.result
     *
     * @mbg.generated
     */
    private Integer result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_log
     *
     * @mbg.generated
     */
    public Charge(Long id, Long car_id, Long use_id, Long mac_id, Double amount, Date time, Integer result, String reason) {
        this.id = id;
        this.car_id = car_id;
        this.use_id = use_id;
        this.mac_id = mac_id;
        this.amount = amount;
        this.time = time;
        this.result = result;
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_log
     *
     * @mbg.generated
     */
    public Charge() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.id
     *
     * @return the value of charge_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.id
     *
     * @param id the value for charge_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.Car_id
     *
     * @return the value of charge_log.Car_id
     *
     * @mbg.generated
     */
    public Long getCar_id() {
        return car_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.Car_id
     *
     * @param car_id the value for charge_log.Car_id
     *
     * @mbg.generated
     */
    public void setCar_id(Long car_id) {
        this.car_id = car_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.Use_id
     *
     * @return the value of charge_log.Use_id
     *
     * @mbg.generated
     */
    public Long getUse_id() {
        return use_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.Use_id
     *
     * @param use_id the value for charge_log.Use_id
     *
     * @mbg.generated
     */
    public void setUse_id(Long use_id) {
        this.use_id = use_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.Mac_id
     *
     * @return the value of charge_log.Mac_id
     *
     * @mbg.generated
     */
    public Long getMac_id() {
        return mac_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.Mac_id
     *
     * @param mac_id the value for charge_log.Mac_id
     *
     * @mbg.generated
     */
    public void setMac_id(Long mac_id) {
        this.mac_id = mac_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.amount
     *
     * @return the value of charge_log.amount
     *
     * @mbg.generated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.amount
     *
     * @param amount the value for charge_log.amount
     *
     * @mbg.generated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.time
     *
     * @return the value of charge_log.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.time
     *
     * @param time the value for charge_log.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.result
     *
     * @return the value of charge_log.result
     *
     * @mbg.generated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.result
     *
     * @param result the value for charge_log.result
     *
     * @mbg.generated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.reason
     *
     * @return the value of charge_log.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.reason
     *
     * @param reason the value for charge_log.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}