package g2.model;

import java.util.Date;

public class Charge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.amount
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.cid
     *
     * @mbg.generated
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.mid
     *
     * @mbg.generated
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.result
     *
     * @mbg.generated
     */
    private Boolean result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_log.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_log
     *
     * @mbg.generated
     */
    public Charge(String id, Long amount, Date time, String uid, String cid, String mid, Boolean result, String reason) {
        this.id = id;
        this.amount = amount;
        this.time = time;
        this.uid = uid;
        this.cid = cid;
        this.mid = mid;
        this.result = result;
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_log
     *
     * @mbg.generated
     */
    public Charge() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.id
     *
     * @return the value of charge_log.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.id
     *
     * @param id the value for charge_log.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.amount
     *
     * @return the value of charge_log.amount
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.amount
     *
     * @param amount the value for charge_log.amount
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.time
     *
     * @return the value of charge_log.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.time
     *
     * @param time the value for charge_log.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.uid
     *
     * @return the value of charge_log.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.uid
     *
     * @param uid the value for charge_log.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.cid
     *
     * @return the value of charge_log.cid
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.cid
     *
     * @param cid the value for charge_log.cid
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.mid
     *
     * @return the value of charge_log.mid
     *
     * @mbg.generated
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.mid
     *
     * @param mid the value for charge_log.mid
     *
     * @mbg.generated
     */
    public void setMid(String mid) {
        this.mid = mid == null ? null : mid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.result
     *
     * @return the value of charge_log.result
     *
     * @mbg.generated
     */
    public Boolean getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.result
     *
     * @param result the value for charge_log.result
     *
     * @mbg.generated
     */
    public void setResult(Boolean result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_log.reason
     *
     * @return the value of charge_log.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_log.reason
     *
     * @param reason the value for charge_log.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}