package g2.model;

public class Machine extends MachineKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Machine.addr
     *
     * @mbg.generated
     */
    private String addr;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    public Machine(String id, String did, String addr) {
        super(id, did);
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    public Machine() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Machine.addr
     *
     * @return the value of Machine.addr
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Machine.addr
     *
     * @param addr the value for Machine.addr
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }
}