package g2.model;

public class Machine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Machine.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Machine.Uni_id
     *
     * @mbg.generated
     */
    private Long uni_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Machine.addr
     *
     * @mbg.generated
     */
    private String addr;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    public Machine(Long id, Long uni_id, String addr) {
        this.id = id;
        this.uni_id = uni_id;
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    public Machine() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Machine.id
     *
     * @return the value of Machine.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Machine.id
     *
     * @param id the value for Machine.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Machine.Uni_id
     *
     * @return the value of Machine.Uni_id
     *
     * @mbg.generated
     */
    public Long getUni_id() {
        return uni_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Machine.Uni_id
     *
     * @param uni_id the value for Machine.Uni_id
     *
     * @mbg.generated
     */
    public void setUni_id(Long uni_id) {
        this.uni_id = uni_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Machine.addr
     *
     * @return the value of Machine.addr
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Machine.addr
     *
     * @param addr the value for Machine.addr
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }
}