package g2.model;

public class Stuff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuff.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuff.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuff.sid
     *
     * @mbg.generated
     */
    private String sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    public Stuff(String id, String name, String sid) {
        this.id = id;
        this.name = name;
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    public Stuff() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuff.id
     *
     * @return the value of stuff.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuff.id
     *
     * @param id the value for stuff.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuff.name
     *
     * @return the value of stuff.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuff.name
     *
     * @param name the value for stuff.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuff.sid
     *
     * @return the value of stuff.sid
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuff.sid
     *
     * @param sid the value for stuff.sid
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }
}