package g2.model;

public class Unit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit.pnum
     *
     * @mbg.generated
     */
    private String pnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Unit
     *
     * @mbg.generated
     */
    public Unit(String id, String type, String account, String password, String pnum) {
        this.id = id;
        this.type = type;
        this.account = account;
        this.password = password;
        this.pnum = pnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Unit
     *
     * @mbg.generated
     */
    public Unit() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit.id
     *
     * @return the value of Unit.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit.id
     *
     * @param id the value for Unit.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit.type
     *
     * @return the value of Unit.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit.type
     *
     * @param type the value for Unit.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit.account
     *
     * @return the value of Unit.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit.account
     *
     * @param account the value for Unit.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit.password
     *
     * @return the value of Unit.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit.password
     *
     * @param password the value for Unit.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit.pnum
     *
     * @return the value of Unit.pnum
     *
     * @mbg.generated
     */
    public String getPnum() {
        return pnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit.pnum
     *
     * @param pnum the value for Unit.pnum
     *
     * @mbg.generated
     */
    public void setPnum(String pnum) {
        this.pnum = pnum == null ? null : pnum.trim();
    }
}