package g2.mapper.java;

import g2.model.Card;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Card
     *
     * @mbg.generated
     */
    @Delete({
        "delete from Card",
        "where 卡号 = #{卡号,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String 卡号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Card
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Card (卡号, 状态, ",
        "余额)",
        "values (#{卡号,jdbcType=VARCHAR}, #{状态,jdbcType=VARCHAR}, ",
        "#{余额,jdbcType=DOUBLE})"
    })
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Card
     *
     * @mbg.generated
     */
    int insertSelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Card
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "卡号, 状态, 余额",
        "from Card",
        "where 卡号 = #{卡号,jdbcType=VARCHAR}"
    })
    @ResultMap("g2.mapper.java.CardMapper.BaseResultMap")
    Card selectByPrimaryKey(String 卡号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Card
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Card
     *
     * @mbg.generated
     */
    @Update({
        "update Card",
        "set 状态 = #{状态,jdbcType=VARCHAR},",
          "余额 = #{余额,jdbcType=DOUBLE}",
        "where 卡号 = #{卡号,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Card record);
}