package g2.mapper.java;

import g2.model.Machine;
import g2.model.MachineKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MachineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    @Delete({
        "delete from Machine",
        "where id = #{id,jdbcType=VARCHAR}",
          "and did = #{did,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(MachineKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Machine (id, did, ",
        "addr)",
        "values (#{id,jdbcType=VARCHAR}, #{did,jdbcType=VARCHAR}, ",
        "#{addr,jdbcType=VARCHAR})"
    })
    int insert(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    int insertSelective(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, did, addr",
        "from Machine",
        "where id = #{id,jdbcType=VARCHAR}",
          "and did = #{did,jdbcType=VARCHAR}"
    })
    @ResultMap("g2.mapper.java.MachineMapper.BaseResultMap")
    Machine selectByPrimaryKey(MachineKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    @Update({
        "update Machine",
        "set addr = #{addr,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}",
          "and did = #{did,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Machine record);
}