package g2.mapper.java;

import g2.model.Schedule;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @Delete({
        "delete from schedule",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @Insert({
        "insert into schedule (id, begin, ",
        "end, address)",
        "values (#{id,jdbcType=VARCHAR}, #{begin,jdbcType=TIMESTAMP}, ",
        "#{end,jdbcType=TIMESTAMP}, #{address,jdbcType=VARCHAR})"
    })
    int insert(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    int insertSelective(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, begin, end, address",
        "from schedule",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("g2.mapper.java.ScheduleMapper.BaseResultMap")
    Schedule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @Update({
        "update schedule",
        "set begin = #{begin,jdbcType=TIMESTAMP},",
          "end = #{end,jdbcType=TIMESTAMP},",
          "address = #{address,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Schedule record);
}