package g2.mapper.java;

import g2.model.Stuff;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface StuffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    @Delete({
        "delete from stuff",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    @Insert({
        "insert into stuff (id, Uni_id, ",
        "sch_id, name)",
        "values (#{id,jdbcType=NUMERIC}, #{uni_id,jdbcType=NUMERIC}, ",
        "#{sch_id,jdbcType=NUMERIC}, #{name,jdbcType=VARCHAR})"
    })
    int insert(Stuff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    int insertSelective(Stuff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, Uni_id, sch_id, name",
        "from stuff",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    @ResultMap("g2.mapper.java.StuffMapper.BaseResultMap")
    Stuff selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Stuff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    @Update({
        "update stuff",
        "set Uni_id = #{uni_id,jdbcType=NUMERIC},",
          "sch_id = #{sch_id,jdbcType=NUMERIC},",
          "name = #{name,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(Stuff record);
}