package g2.mapper.java;

import g2.mapper.Extension.User;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserMapper extends User {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    @Delete({
        "delete from Users",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Users (id, Car_id, ",
        "name, password, ",
        "usertype, type)",
        "values (#{id,jdbcType=NUMERIC}, #{car_id,jdbcType=NUMERIC}, ",
        "#{name,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{usertype,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER})"
    })
    int insert(g2.model.User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    int insertSelective(g2.model.User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, Car_id, name, password, usertype, type",
        "from Users",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    @ResultMap("g2.mapper.java.UserMapper.BaseResultMap")
    g2.model.User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(g2.model.User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    @Update({
        "update Users",
        "set Car_id = #{car_id,jdbcType=NUMERIC},",
          "name = #{name,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "usertype = #{usertype,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(g2.model.User record);
}