package g2.mapper.java;

import g2.model.User;
import g2.model.UserKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated
     */
    @Delete({
        "delete from User",
        "where name = #{name,jdbcType=VARCHAR}",
          "and password = #{password,jdbcType=VARCHAR}",
          "and type = #{type,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated
     */
    @Insert({
        "insert into User (name, password, ",
        "type, id, cid)",
        "values (#{name,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{id,jdbcType=VARCHAR}, #{cid,jdbcType=VARCHAR})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "name, password, type, id, cid",
        "from User",
        "where name = #{name,jdbcType=VARCHAR}",
          "and password = #{password,jdbcType=VARCHAR}",
          "and type = #{type,jdbcType=VARCHAR}"
    })
    @ResultMap("g2.mapper.java.UserMapper.BaseResultMap")
    User selectByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated
     */
    @Update({
        "update User",
        "set id = #{id,jdbcType=VARCHAR},",
          "cid = #{cid,jdbcType=VARCHAR}",
        "where name = #{name,jdbcType=VARCHAR}",
          "and password = #{password,jdbcType=VARCHAR}",
          "and type = #{type,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(User record);
}