package g2.model;

import java.util.Date;

public class Charge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chargelog.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chargelog.Car_id
     *
     * @mbg.generated
     */
    private Long car_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chargelog.Mac_id
     *
     * @mbg.generated
     */
    private Long mac_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chargelog.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chargelog.amount
     *
     * @mbg.generated
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chargelog.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chargelog.result
     *
     * @mbg.generated
     */
    private Integer result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chargelog.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargelog
     *
     * @mbg.generated
     */
    public Charge(Long id, Long car_id, Long mac_id, String name, Double amount, Date time, Integer result, String reason) {
        this.id = id;
        this.car_id = car_id;
        this.mac_id = mac_id;
        this.name = name;
        this.amount = amount;
        this.time = time;
        this.result = result;
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargelog
     *
     * @mbg.generated
     */
    public Charge() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chargelog.id
     *
     * @return the value of chargelog.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chargelog.id
     *
     * @param id the value for chargelog.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chargelog.Car_id
     *
     * @return the value of chargelog.Car_id
     *
     * @mbg.generated
     */
    public Long getCar_id() {
        return car_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chargelog.Car_id
     *
     * @param car_id the value for chargelog.Car_id
     *
     * @mbg.generated
     */
    public void setCar_id(Long car_id) {
        this.car_id = car_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chargelog.Mac_id
     *
     * @return the value of chargelog.Mac_id
     *
     * @mbg.generated
     */
    public Long getMac_id() {
        return mac_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chargelog.Mac_id
     *
     * @param mac_id the value for chargelog.Mac_id
     *
     * @mbg.generated
     */
    public void setMac_id(Long mac_id) {
        this.mac_id = mac_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chargelog.name
     *
     * @return the value of chargelog.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chargelog.name
     *
     * @param name the value for chargelog.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chargelog.amount
     *
     * @return the value of chargelog.amount
     *
     * @mbg.generated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chargelog.amount
     *
     * @param amount the value for chargelog.amount
     *
     * @mbg.generated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chargelog.time
     *
     * @return the value of chargelog.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chargelog.time
     *
     * @param time the value for chargelog.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chargelog.result
     *
     * @return the value of chargelog.result
     *
     * @mbg.generated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chargelog.result
     *
     * @param result the value for chargelog.result
     *
     * @mbg.generated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chargelog.reason
     *
     * @return the value of chargelog.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chargelog.reason
     *
     * @param reason the value for chargelog.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}