package g2.model;

import java.util.Date;

public class Consume {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumelog.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumelog.Car_id
     *
     * @mbg.generated
     */
    private Long car_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumelog.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumelog.amount
     *
     * @mbg.generated
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumelog.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumelog.result
     *
     * @mbg.generated
     */
    private Integer result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumelog.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumelog
     *
     * @mbg.generated
     */
    public Consume(Long id, Long car_id, String name, Double amount, Date time, Integer result, String reason) {
        this.id = id;
        this.car_id = car_id;
        this.name = name;
        this.amount = amount;
        this.time = time;
        this.result = result;
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumelog
     *
     * @mbg.generated
     */
    public Consume() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumelog.id
     *
     * @return the value of consumelog.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumelog.id
     *
     * @param id the value for consumelog.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumelog.Car_id
     *
     * @return the value of consumelog.Car_id
     *
     * @mbg.generated
     */
    public Long getCar_id() {
        return car_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumelog.Car_id
     *
     * @param car_id the value for consumelog.Car_id
     *
     * @mbg.generated
     */
    public void setCar_id(Long car_id) {
        this.car_id = car_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumelog.name
     *
     * @return the value of consumelog.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumelog.name
     *
     * @param name the value for consumelog.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumelog.amount
     *
     * @return the value of consumelog.amount
     *
     * @mbg.generated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumelog.amount
     *
     * @param amount the value for consumelog.amount
     *
     * @mbg.generated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumelog.time
     *
     * @return the value of consumelog.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumelog.time
     *
     * @param time the value for consumelog.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumelog.result
     *
     * @return the value of consumelog.result
     *
     * @mbg.generated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumelog.result
     *
     * @param result the value for consumelog.result
     *
     * @mbg.generated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumelog.reason
     *
     * @return the value of consumelog.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumelog.reason
     *
     * @param reason the value for consumelog.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}