package g2.model;

import java.util.Date;

public class Schedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.start
     *
     * @mbg.generated
     */
    private Date start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.stop
     *
     * @mbg.generated
     */
    private Date stop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    public Schedule(Long id, Date start, Date stop, String address) {
        this.id = id;
        this.start = start;
        this.stop = stop;
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    public Schedule() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.id
     *
     * @return the value of schedule.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.id
     *
     * @param id the value for schedule.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.start
     *
     * @return the value of schedule.start
     *
     * @mbg.generated
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.start
     *
     * @param start the value for schedule.start
     *
     * @mbg.generated
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.stop
     *
     * @return the value of schedule.stop
     *
     * @mbg.generated
     */
    public Date getStop() {
        return stop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.stop
     *
     * @param stop the value for schedule.stop
     *
     * @mbg.generated
     */
    public void setStop(Date stop) {
        this.stop = stop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.address
     *
     * @return the value of schedule.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.address
     *
     * @param address the value for schedule.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}