package g2.model;

public class Usertype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertype.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertype
     *
     * @mbg.generated
     */
    public Usertype(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertype
     *
     * @mbg.generated
     */
    public Usertype() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertype.type
     *
     * @return the value of usertype.type
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertype.type
     *
     * @param type the value for usertype.type
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}