package g2.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.Car_id
     *
     * @mbg.generated
     */
    private Long car_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.usertype
     *
     * @mbg.generated
     */
    private String usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    public User(String name, Long car_id, String password, String usertype, Integer type) {
        this.name = name;
        this.car_id = car_id;
        this.password = password;
        this.usertype = usertype;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.name
     *
     * @return the value of Users.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.name
     *
     * @param name the value for Users.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.Car_id
     *
     * @return the value of Users.Car_id
     *
     * @mbg.generated
     */
    public Long getCar_id() {
        return car_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.Car_id
     *
     * @param car_id the value for Users.Car_id
     *
     * @mbg.generated
     */
    public void setCar_id(Long car_id) {
        this.car_id = car_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.password
     *
     * @return the value of Users.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.password
     *
     * @param password the value for Users.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.usertype
     *
     * @return the value of Users.usertype
     *
     * @mbg.generated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.usertype
     *
     * @param usertype the value for Users.usertype
     *
     * @mbg.generated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.type
     *
     * @return the value of Users.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.type
     *
     * @param type the value for Users.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}