package g2.mapper;

import g2.model.Charge;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ChargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargelog
     *
     * @mbg.generated
     */
    @Delete({
        "delete from chargelog",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargelog
     *
     * @mbg.generated
     */
    @Insert({
        "insert into chargelog (id, Car_id, ",
        "Mac_id, name, amount, ",
        "time, result, ",
        "reason)",
        "values (#{id,jdbcType=NUMERIC}, #{car_id,jdbcType=NUMERIC}, ",
        "#{mac_id,jdbcType=NUMERIC}, #{name,jdbcType=VARCHAR}, #{amount,jdbcType=DOUBLE}, ",
        "#{time,jdbcType=TIMESTAMP}, #{result,jdbcType=INTEGER}, ",
        "#{reason,jdbcType=VARCHAR})"
    })
    int insert(Charge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargelog
     *
     * @mbg.generated
     */
    int insertSelective(Charge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargelog
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, Car_id, Mac_id, name, amount, time, result, reason",
        "from chargelog",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    @ResultMap("g2.mapper.ChargeMapper.BaseResultMap")
    Charge selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargelog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Charge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargelog
     *
     * @mbg.generated
     */
    @Update({
        "update chargelog",
        "set Car_id = #{car_id,jdbcType=NUMERIC},",
          "Mac_id = #{mac_id,jdbcType=NUMERIC},",
          "name = #{name,jdbcType=VARCHAR},",
          "amount = #{amount,jdbcType=DOUBLE},",
          "time = #{time,jdbcType=TIMESTAMP},",
          "result = #{result,jdbcType=INTEGER},",
          "reason = #{reason,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(Charge record);
}