package g2.mapper;

import g2.model.Machine;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MachineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    @Delete({
        "delete from Machine",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Machine (id, Uni_id, ",
        "addr)",
        "values (#{id,jdbcType=NUMERIC}, #{uni_id,jdbcType=NUMERIC}, ",
        "#{addr,jdbcType=VARCHAR})"
    })
    int insert(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    int insertSelective(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, Uni_id, addr",
        "from Machine",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    @ResultMap("g2.mapper.MachineMapper.BaseResultMap")
    Machine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Machine
     *
     * @mbg.generated
     */
    @Update({
        "update Machine",
        "set Uni_id = #{uni_id,jdbcType=NUMERIC},",
          "addr = #{addr,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(Machine record);
}