package g2.mapper;

import g2.mapper.Extra.UsertypeExt;
import g2.model.Usertype;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;

public interface UsertypeMapper extends UsertypeExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertype
     *
     * @mbg.generated
     */
    @Delete({
            "delete from usertype",
            "where type = #{type,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertype
     *
     * @mbg.generated
     */
    @Insert({
            "insert into usertype (type)",
            "values (#{type,jdbcType=VARCHAR})"
    })
    int insert(Usertype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertype
     *
     * @mbg.generated
     */
    int insertSelective(Usertype record);
}