package g2.mapper;

import g2.mapper.Extra.UserExt;
import g2.model.User;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserMapper extends UserExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    @Delete({
        "delete from Users",
        "where name = #{name,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    @Insert({
        "insert into Users (name, Car_id, ",
            "password, type)",
        "values (#{name,jdbcType=VARCHAR}, #{car_id,jdbcType=NUMERIC}, ",
            "#{password,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    @Select({
        "select",
            "name, Car_id, password, type",
        "from Users",
        "where name = #{name,jdbcType=VARCHAR}"
    })
    @ResultMap("g2.mapper.UserMapper.BaseResultMap")
    User selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Users
     *
     * @mbg.generated
     */
    @Update({
        "update Users",
        "set Car_id = #{car_id,jdbcType=NUMERIC},",
          "password = #{password,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER}",
        "where name = #{name,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(User record);
}